#!/bin/sh
TESSERACTVERSION=$(tesseract -v 2>&1| cut -f2 -d' ')
INGRESSPROFILE=$1
TEMPFILE=$(mktemp)
if [ "${TESSERACTVERSION}" = "3.03" ]; then
	tesseract -psm 4 $INGRESSPROFILE stdout > $TEMPFILE 2>/dev/null
else
	tesseract -psm 6 $INGRESSPROFILE $TEMPFILE >/dev/null 2>&1
	mv -f $TEMPFILE.txt $TEMPFILE
fi
INGRESSUSER=$(grep -A2 AGENT $TEMPFILE | fgrep -v "LVL" | egrep "[a-z]" | tail -1 | sed 's/[^a-zA-Z]//g')
echo "Username $INGRESSUSER"
fgrep " AP" $TEMPFILE | sed 's/,//g' | sed -r "s/^.* ([0-9]+* AP) .*$/\1/g"
egrep "^Unique Portals Visited|\
^Portals Discovered|\
^XM Collected|\
^Hacks|\
^Resonators Deployed|\
^Links Created|\
^Control Fields Created|\
^Mind Units Captured|\
^Longest Link Ever Created|\
^Largest Control Field|\
^XM Recharged|\
^Portals Captured|\
^Unique Portals Captured|\
^Resonators Destroyed|\
^Portals Neutralized|\
^Enemy Links Destroyed|\
^Enemy Control Fields Destroyed|\
^Distance Walked|\
^Max Time Portal Held|\
^Max Time Link Maintained|\
^Max Link Length x Days|\
^Max Time Field Held|\
^Max Time Field Held|\
^Largest Field MUs x Days" \
$TEMPFILE \
| sed 's/\\\_\/ //' \
| sed 's/ <2//'
rm -f $TEMPFILE
